version: "3.9"
services:
  api:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: hadara
      POSTGRES_PASSWORD: hadara
      POSTGRES_DB: hadara
    ports:
      - "5432:5432"
    volumes:
      - hadara_db_data:/var/lib/postgresql/data

volumes:
  hadara_db_data:
